export const getQuerySearchKey = (search) => ['productsfetch', search]
export const getQueryCartKey = (cart) => ['cart', cart]
export const getQueryUserKey = () => ['user']
export const getQueryProductKey = () => ['product']
export const getQueryCommentsKey = () => ['comments']
